// Datos de ejemplo para clientes
export const clientesData = [
  {
    id: "1",
    tipo: "despachante",
    cuit: "20-12345678-9",
    razonSocial: "Despachante Logística Internacional S.A.",
    condicionIva: "Responsable Inscripto",
    domicilio: "Av. Corrientes 1234, Piso 5",
    razonSocialEmpresa: "Importadora Global S.R.L.",
    domicilioEmpresa: "",
    localidad: "Ciudad Autónoma de Buenos Aires",
    rubro: "Logística y Comercio Exterior",
  },
  {
    id: "2",
    tipo: "despachante",
    cuit: "30-98765432-1",
    razonSocial: "Aduanas Express S.A.",
    condicionIva: "Responsable Inscripto",
    domicilio: "Calle San Martín 567",
    razonSocialEmpresa: "Exportadora Nacional",
    domicilioEmpresa: "Av. del Libertador 1500",
    localidad: "Rosario",
    rubro: "Comercio Internacional",
  },
  {
    id: "3",
    tipo: "cliente",
    cuit: "33-55667788-9",
    razonSocial: "Manufacturas Argentinas S.A.",
    condicionIva: "Responsable Inscripto",
    domicilio: "Ruta 9 Km 32.5, Parque Industrial",
    localidad: "Pilar",
    rubro: "Industria Manufacturera",
  },
  {
    id: "4",
    tipo: "cliente",
    cuit: "27-44332211-0",
    razonSocial: "Distribuidora del Sur",
    condicionIva: "Monotributista",
    domicilio: "Av. Hipólito Yrigoyen 350",
    localidad: "Córdoba",
    rubro: "Distribución Mayorista",
  },
  {
    id: "5",
    tipo: "despachante",
    cuit: "20-33445566-7",
    razonSocial: "Despachos Marítimos S.R.L.",
    condicionIva: "Responsable Inscripto",
    domicilio: "Puerto Nuevo, Dársena E",
    razonSocialEmpresa: "Naviera Internacional",
    domicilioEmpresa: "",
    localidad: "Ciudad Autónoma de Buenos Aires",
    rubro: "Transporte Marítimo",
  },
]
